### ISSUE TITLE
Weird select style on Firexox

### ISSUE THREAD

**Issue by ellipticaldoor** [milligram/milligram#161]
Firefox doesn't show the down arrow and also presents a border inside the input.

This happens on the latest version of firefox (52.0.2 (64-bit)) for macos.

![image](https://cloud.githubusercontent.com/assets/3449006/25070063/583d853a-228b-11e7-885a-55df5dc2dcb3.png)

**Comment by imsurinder90** [comment]
The background base64 svg encoded url is not parsed well in firefox due to following reason:
1. Double quotes are getting escaped.
2. '#' in '#d1d1d1' must be encoded like '%23d1d1d1'

The resulted url is:

`data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" height="14" viewBox="0 0 29 14" width="29"><path fill="%23d1d1d1" d="M9.37727 3.625l5.08154 6.93523L19.54036 3.625"/></svg>`

I made these changes into base64 svg url and it works.

**Comment by JulienJo** [comment]
@imsurinder90 nice!

**Comment by cjpatoilo** [comment]
Before Milligram made use of base64 img but this generated considerable weight. So we decided to upgrade to what you see today. 

@imsurinder90 Could you show me how it would look (weight) using base64 svg?

**Comment by imsurinder90** [comment]
I have already sent a PR. Have a look
https://github.com/milligram/milligram/pull/166

and let me know if any changes.

**Comment by cjpatoilo** [comment]
Sorry for the delay, I'll test. When I answered you I mentioned what you said about base64.

**Comment by meghprkh** [comment]
@cjpatoilo Can a new release be released with the fix of the select box since it is already merged? Thanks. (currently to circumvent this I have to add these rules in my main css file)

**Comment by paniclater** [comment]
Came here to see if I could help out with this, I'm also experiencing this issue, but it looks like there is already a proposed solution merged. Has there been an updated release with this fix? Thank you for a great framework, really enjoying your work!

**Comment by cjpatoilo** [comment]
@ellipticaldoor this issue was fixed. For now, I will close this issue.
Please, feel free to reopen or open a new one.
