### ISSUE TITLE
Is this package still active?

### ISSUE THREAD

**Issue by SampsonCrowley** [milligram/milligram#239]
There are lots of open pull requests, but there hasn't been any new commits since june

**Comment by robsheldon** [comment]
I like milligram and hope it gets updated again soon.

I've stitched together an alternative option at https://github.com/robsheldon/sscaffold-css

The bad: it's a bit heavier than milligram (about 1.3 milligrams, heh). Fonts & colors have been changed (mostly because it would be uncool to straight copy milligram's), but can be easily overridden. There are a few other small but important differences for sites already using milligram.

The not so bad: it includes a current normalize.css, support for skeleton's 12-column grid if you want it, the css has been restructured to be easy to edit and/or build your own theme, and there's full documentation available.

If it's super rude to link to another alternative like this, just yell at me and I'll delete the comment.

**Comment by SampsonCrowley** [comment]
@robsheldon well if it's rude to link to an alternative in a repo that doesn't get a response to even basic questions, I'd say it's even more rude for the maintainers here to not at least transfer ownership to someone who DOES have time to maintain it when there are obviously so many people interested in making it better

**Comment by schirrel** [comment]
@robsheldon and @cjpatoilo i'de like to be a maintainer, i like the project a lot, even add sobre prs.

I'd appreciate if you guys think about it

**Comment by szul** [comment]
@schirrel Has @cjpatoilo gotten back to you on this? I use this in a lot of projects and would rather not fork it to maintain it separately.

**Comment by cjpatoilo** [comment]
I'm back!

@SampsonCrowley yes, Milligram is still active!
@robsheldon congrats, great project! 
@schirrel you can help by answering questions about how to use or test and fix problems related to errors.
@szul I always appreciate you here. So, I just need to resolve some tests in the new table style before launching the new version `v1.14.0`.

Also, let me know if there are any issues that should be considered a priority.

**Comment by galiprandi** [comment]
Great proyect!
Greetings from Argentina.

**Comment by cjpatoilo** [comment]
@galiprandi thank you 🙏 

> Great proyect!
> Greetings from Argentina.

**Comment by cjpatoilo** [comment]
For now, I will close this issue.
