### ISSUE TITLE
@necolas/normalize.css vs @csstools/normalize.css

### ISSUE THREAD

**Issue by graymatter00** [milligram/milligram#264]
This is not an Issue - more of a request for advice.

I'm planning to use Milligram in a new project.  Milligram uses @necolas/normalize.css: https://github.com/necolas/normalize.css.  That project seems to be to all but dead.  See necolas/normalize.css#805.  The last update was November 2018, and many PRs seems to have been ignored.

I'm considering using @csstools/normalize.css instead: https://github.com/csstools/normalize.css.  Has anyone else used this with Milligram?  Can anyone think of a reason not to use this?  Any other thoughts or suggestions on this are appreciated.

**Comment by ghost** [comment]
Hi I tried it. But that doesn't make things easier they almost the same cause almost all issues reported in  necolas/normalize.css are not fixed. And the csstools/normalize.css is also the same thing from the same team. They do occasional commits like in 3-4 months. And the build is failing since December. I solved the issue and created a new css reset that is updated with time. It is new and ❤ contributions/suggestions. Check the repo https://github.com/krishdevdb/reseter.css

**Comment by graymatter00** [comment]
> Hi I tried it. But that doesn't make things easier they almost the same cause almost all issues reported in necolas/normalize.css are not fixed. And the csstools/normalize.css is also the same thing from the same team. They do occasional commits like in 3-4 months. And the build is failing since December. I solved the issue and created a new css reset that is updated with time. It is new and ❤ contributions/suggestions. Check the repo https://github.com/krishdevdb/reseter.css

**Comment by graymatter00** [comment]
@krishdevdb  Thanks for your reply.  And I understand your comments about the two normalize.css variants.  I'll give your reseter.css a good look.

**Comment by ghost** [comment]
Thanks for being interested in my project. **Don't Forget To See The Versus Section. You Will Get To Know What All Is Included**
