### ISSUE TITLE
Pre Overflow

### ISSUE THREAD

**Issue by plfstr** [milligram/milligram#42]
Pre code blocks with long lines break out of their containers, seen here on the [milligram site](https://milligram.github.io/)

**Comment by vkeusebio** [comment]
I'm thinking of either putting a scroll-bar (which won't look pretty) or wrapping the text.

**Comment by rodrigoddalmeida** [comment]
The main two options are:

1. setting the white-space property to `pre-wrap` (will wrap the text)
2. setting the overflow property to `auto` (will scroll when needed)

I believe scrolling is the best option, since we may want to actually preserve character position in the code tag. What do you think?

**Comment by cjpatoilo** [comment]
I had noticed as well. "This request has been blocked; the content must be served over HTTPS."
![image](https://cloud.githubusercontent.com/assets/1542831/12370192/5fcb168a-bbe6-11e5-9f0e-53997b5456e2.png)

BTW thanks for the PR @plfstr
