### ISSUE TITLE
Flexbox options

### ISSUE THREAD

**Issue by rkb81** [milligram/milligram#43]
I not found option in flexbox grid to set position and another options exists, I'm testing with https://github.com/matthewsimo/scss-flex-grid to integrate this functions.

**Comment by cjpatoilo** [comment]
That's true! Could you send a pull request with your test?

**Comment by valerielitman** [comment]
Hi @rkb81,
I had some problems with the flexbox grid when I used Milligram SCSS.  I went into the grid.css file and played around with .row. I removed `flex-direction: column;`. I also removed some of the nesting so that .row ends here and no longer includes the column classes:

```
.row {
	display: flex;
	padding: 0;
	width: 100%;
	.row-wrap {
		flex-wrap: wrap;
	}
	.row-no-padding {
		padding: 0;
		& > .column {
			padding: 0;
		}
	}
}

```

Let me know if that helps!

**Comment by cjpatoilo** [comment]
Hi @rkb81 @valerielitman Let me know if there are any questions and I will reopen this question to answer them. For now I will close this issue, thanks.
