### ISSUE TITLE
Ability to Input Data Into Tables

### ISSUE THREAD

**Issue by TheoBearman** [milligram/milligram#6]
Good evening,

I am running a [website](https://vatsim.theobearman.com/) using Bootstrap 3 (yawn) which displays some data in tables pulled from an API. I am really keen to revamp this website with something more minimal such as Milligram or Skeleton. The one thing that is preventing me from doing so is that, to my knowledge, Milligram nor Skeleton has the table functionality I can achieve using [Bootstrap Table](http://bootstrap-table.wenzhixin.net.cn/). The key functionality I need is to be able to inject the contents of multiple .json files that have been pulled using a php file.

Is there any intention from the Milligram developers to make these kind of functions available for the tables?

Thanks very much in advance.

**Comment by MrTarantula** [comment]
I can't speak for the maintainers of this project, but I believe what you are wanting falls outside of the scope of milligram's goals. They likely want to keep the framework as small as possible, and adding the functionality you're requesting could increase the size by 25% or more.

As you have stated, Bootstrap alone does not have this functionality either. Bootstrap Table is essentially some jQuery functions to pull in data. It uses its own CSS instead of relying on Bootstrap, so the CSS should be easily modifiable. You could modify Bootstrap Table's CSS to use milligram's styling instead. Alternatively, there are several frontend frameworks that you can use along with milligram to easily get this functionality (and much much more), such as [Angular](https://github.com/angular/angular.js), [React](https://github.com/facebook/react), and [Aurelia](https://github.com/durandalproject/aurelia).

**Comment by cjpatoilo** [comment]
Exactly. Milligram provides a minimal configuration for a quick and clean starting point. Unfortunately, there is no support for JavaScript. But if you join Milligram any other JS framework, or library, you can build something really cool as you wish. If you need help with something, call me [here](https://github.com/cjpatoilo/ama). 

Guys, thanks so much!

**Comment by thompsonemerson** [comment]
@MrTarantula +1

**Comment by adcoolguy** [comment]
Also, not sure if this is a bit out of topic but we are wondering why the table style looks so ugly compared with Bootstrap's table? Do you have style like "table table-striped table-bordered"?
